<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cash on Delivery_payment_method_ppec_paypal</name>
   <tag></tag>
   <elementGuidId>5ccb823f-f096-4930-a661-f47c78af1aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_ppec_paypal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment_method_ppec_paypal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c80e6bbe-cd80-43da-a8f8-546ec5488ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_ppec_paypal</value>
      <webElementGuid>9dc58407-0813-4e61-a70e-c273dad23f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c4bea4c2-1275-48f4-839e-46f559ed688d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>2fa04e76-2a5f-42fb-a3d4-0be73877d9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>b2f4d478-f18f-4499-98dd-c6c57d06417d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ppec_paypal</value>
      <webElementGuid>43234c28-59d2-400a-b4ff-0693b1089c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-order_button_text</name>
      <type>Main</type>
      <value>Continue to payment</value>
      <webElementGuid>3d15552a-ad7c-4872-817b-25b17183b0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_ppec_paypal&quot;)</value>
      <webElementGuid>afa27a73-b3cc-4229-8aca-8d32af835a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>5b5c98d4-6bcf-4de0-8445-9ed23e6025ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_ppec_paypal']</value>
      <webElementGuid>77826d65-e0a5-423a-b99e-4560338fcaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li[4]/input</value>
      <webElementGuid>6ed2b06b-f205-4710-b329-5af8bc057dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/input</value>
      <webElementGuid>d86dfb03-ef1d-47ca-9ab2-3b759d832263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_ppec_paypal' and @type = 'radio' and @name = 'payment_method' and @checked = 'checked']</value>
      <webElementGuid>673e9c09-e79e-4ebb-a83c-1a4dcaada698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_ppec_paypal' and @type = 'radio' and @name = 'payment_method']</value>
      <webElementGuid>83fad174-e2e4-404c-9404-78655a4b2c40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
